/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/app'
import { Route as AiVoiceAgentForWebsiteRouteImport } from './routes/ai-voice-agent-for-website'
import { Route as AiChatbotTrainedOnYourWebsiteRouteImport } from './routes/ai-chatbot-trained-on-your-website'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WidgetSoulIdRouteImport } from './routes/widget.$soulId'
import { Route as AuthPathnameRouteImport } from './routes/auth.$pathname'
import { Route as ApiWorkspaceRouteImport } from './routes/api.workspace'
import { Route as ApiScanRouteImport } from './routes/api.scan'
import { Route as ApiIngestRouteImport } from './routes/api.ingest'
import { Route as ApiChatRouteImport } from './routes/api.chat'
import { Route as ApiWebhooksTestRouteImport } from './routes/api.webhooks.test'
import { Route as ApiVoiceSpeakRouteImport } from './routes/api.voice.speak'
import { Route as ApiVoiceProfilesRouteImport } from './routes/api.voice.profiles'
import { Route as ApiVoiceCloneRouteImport } from './routes/api.voice.clone'
import { Route as ApiSoulsPublishRouteImport } from './routes/api.souls.publish'
import { Route as ApiSoulsSoulIdRouteImport } from './routes/api.souls.$soulId'
import { Route as ApiIngestStreamRouteImport } from './routes/api.ingest.stream'
import { Route as ApiChatStreamRouteImport } from './routes/api.chat.stream'
import { Route as ApiBillingWebhookRouteImport } from './routes/api.billing.webhook'
import { Route as ApiBillingSummaryRouteImport } from './routes/api.billing.summary'
import { Route as ApiBillingInvoicesRouteImport } from './routes/api.billing.invoices'
import { Route as ApiBillingConfirmRouteImport } from './routes/api.billing.confirm'
import { Route as ApiBillingCheckoutRouteImport } from './routes/api.billing.checkout'
import { Route as ApiBillingChangeRouteImport } from './routes/api.billing.change'
import { Route as ApiBillingCancelRouteImport } from './routes/api.billing.cancel'
import { Route as ApiWidgetsSoulIdSessionRouteImport } from './routes/api.widgets.$soulId.session'
import { Route as ApiSoulsSoulIdEventsRouteImport } from './routes/api.souls.$soulId.events'
import { Route as ApiInternalWebhooksDrainRouteImport } from './routes/api.internal.webhooks.drain'

const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AiVoiceAgentForWebsiteRoute = AiVoiceAgentForWebsiteRouteImport.update({
  id: '/ai-voice-agent-for-website',
  path: '/ai-voice-agent-for-website',
  getParentRoute: () => rootRouteImport,
} as any)
const AiChatbotTrainedOnYourWebsiteRoute =
  AiChatbotTrainedOnYourWebsiteRouteImport.update({
    id: '/ai-chatbot-trained-on-your-website',
    path: '/ai-chatbot-trained-on-your-website',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WidgetSoulIdRoute = WidgetSoulIdRouteImport.update({
  id: '/widget/$soulId',
  path: '/widget/$soulId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathnameRoute = AuthPathnameRouteImport.update({
  id: '/auth/$pathname',
  path: '/auth/$pathname',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiScanRoute = ApiScanRouteImport.update({
  id: '/api/scan',
  path: '/api/scan',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestRoute = ApiIngestRouteImport.update({
  id: '/api/ingest',
  path: '/api/ingest',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksTestRoute = ApiWebhooksTestRouteImport.update({
  id: '/api/webhooks/test',
  path: '/api/webhooks/test',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceSpeakRoute = ApiVoiceSpeakRouteImport.update({
  id: '/api/voice/speak',
  path: '/api/voice/speak',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceProfilesRoute = ApiVoiceProfilesRouteImport.update({
  id: '/api/voice/profiles',
  path: '/api/voice/profiles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVoiceCloneRoute = ApiVoiceCloneRouteImport.update({
  id: '/api/voice/clone',
  path: '/api/voice/clone',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoulsPublishRoute = ApiSoulsPublishRouteImport.update({
  id: '/api/souls/publish',
  path: '/api/souls/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoulsSoulIdRoute = ApiSoulsSoulIdRouteImport.update({
  id: '/api/souls/$soulId',
  path: '/api/souls/$soulId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiIngestStreamRoute = ApiIngestStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiIngestRoute,
} as any)
const ApiChatStreamRoute = ApiChatStreamRouteImport.update({
  id: '/stream',
  path: '/stream',
  getParentRoute: () => ApiChatRoute,
} as any)
const ApiBillingWebhookRoute = ApiBillingWebhookRouteImport.update({
  id: '/api/billing/webhook',
  path: '/api/billing/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingSummaryRoute = ApiBillingSummaryRouteImport.update({
  id: '/api/billing/summary',
  path: '/api/billing/summary',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingInvoicesRoute = ApiBillingInvoicesRouteImport.update({
  id: '/api/billing/invoices',
  path: '/api/billing/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingConfirmRoute = ApiBillingConfirmRouteImport.update({
  id: '/api/billing/confirm',
  path: '/api/billing/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCheckoutRoute = ApiBillingCheckoutRouteImport.update({
  id: '/api/billing/checkout',
  path: '/api/billing/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingChangeRoute = ApiBillingChangeRouteImport.update({
  id: '/api/billing/change',
  path: '/api/billing/change',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBillingCancelRoute = ApiBillingCancelRouteImport.update({
  id: '/api/billing/cancel',
  path: '/api/billing/cancel',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWidgetsSoulIdSessionRoute = ApiWidgetsSoulIdSessionRouteImport.update({
  id: '/api/widgets/$soulId/session',
  path: '/api/widgets/$soulId/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSoulsSoulIdEventsRoute = ApiSoulsSoulIdEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => ApiSoulsSoulIdRoute,
} as any)
const ApiInternalWebhooksDrainRoute =
  ApiInternalWebhooksDrainRouteImport.update({
    id: '/api/internal/webhooks/drain',
    path: '/api/internal/webhooks/drain',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-chatbot-trained-on-your-website': typeof AiChatbotTrainedOnYourWebsiteRoute
  '/ai-voice-agent-for-website': typeof AiVoiceAgentForWebsiteRoute
  '/app': typeof AppRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/ingest': typeof ApiIngestRouteWithChildren
  '/api/scan': typeof ApiScanRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/widget/$soulId': typeof WidgetSoulIdRoute
  '/api/billing/cancel': typeof ApiBillingCancelRoute
  '/api/billing/change': typeof ApiBillingChangeRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/confirm': typeof ApiBillingConfirmRoute
  '/api/billing/invoices': typeof ApiBillingInvoicesRoute
  '/api/billing/summary': typeof ApiBillingSummaryRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/ingest/stream': typeof ApiIngestStreamRoute
  '/api/souls/$soulId': typeof ApiSoulsSoulIdRouteWithChildren
  '/api/souls/publish': typeof ApiSoulsPublishRoute
  '/api/voice/clone': typeof ApiVoiceCloneRoute
  '/api/voice/profiles': typeof ApiVoiceProfilesRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/webhooks/test': typeof ApiWebhooksTestRoute
  '/api/internal/webhooks/drain': typeof ApiInternalWebhooksDrainRoute
  '/api/souls/$soulId/events': typeof ApiSoulsSoulIdEventsRoute
  '/api/widgets/$soulId/session': typeof ApiWidgetsSoulIdSessionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-chatbot-trained-on-your-website': typeof AiChatbotTrainedOnYourWebsiteRoute
  '/ai-voice-agent-for-website': typeof AiVoiceAgentForWebsiteRoute
  '/app': typeof AppRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/ingest': typeof ApiIngestRouteWithChildren
  '/api/scan': typeof ApiScanRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/widget/$soulId': typeof WidgetSoulIdRoute
  '/api/billing/cancel': typeof ApiBillingCancelRoute
  '/api/billing/change': typeof ApiBillingChangeRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/confirm': typeof ApiBillingConfirmRoute
  '/api/billing/invoices': typeof ApiBillingInvoicesRoute
  '/api/billing/summary': typeof ApiBillingSummaryRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/ingest/stream': typeof ApiIngestStreamRoute
  '/api/souls/$soulId': typeof ApiSoulsSoulIdRouteWithChildren
  '/api/souls/publish': typeof ApiSoulsPublishRoute
  '/api/voice/clone': typeof ApiVoiceCloneRoute
  '/api/voice/profiles': typeof ApiVoiceProfilesRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/webhooks/test': typeof ApiWebhooksTestRoute
  '/api/internal/webhooks/drain': typeof ApiInternalWebhooksDrainRoute
  '/api/souls/$soulId/events': typeof ApiSoulsSoulIdEventsRoute
  '/api/widgets/$soulId/session': typeof ApiWidgetsSoulIdSessionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-chatbot-trained-on-your-website': typeof AiChatbotTrainedOnYourWebsiteRoute
  '/ai-voice-agent-for-website': typeof AiVoiceAgentForWebsiteRoute
  '/app': typeof AppRoute
  '/api/chat': typeof ApiChatRouteWithChildren
  '/api/ingest': typeof ApiIngestRouteWithChildren
  '/api/scan': typeof ApiScanRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/auth/$pathname': typeof AuthPathnameRoute
  '/widget/$soulId': typeof WidgetSoulIdRoute
  '/api/billing/cancel': typeof ApiBillingCancelRoute
  '/api/billing/change': typeof ApiBillingChangeRoute
  '/api/billing/checkout': typeof ApiBillingCheckoutRoute
  '/api/billing/confirm': typeof ApiBillingConfirmRoute
  '/api/billing/invoices': typeof ApiBillingInvoicesRoute
  '/api/billing/summary': typeof ApiBillingSummaryRoute
  '/api/billing/webhook': typeof ApiBillingWebhookRoute
  '/api/chat/stream': typeof ApiChatStreamRoute
  '/api/ingest/stream': typeof ApiIngestStreamRoute
  '/api/souls/$soulId': typeof ApiSoulsSoulIdRouteWithChildren
  '/api/souls/publish': typeof ApiSoulsPublishRoute
  '/api/voice/clone': typeof ApiVoiceCloneRoute
  '/api/voice/profiles': typeof ApiVoiceProfilesRoute
  '/api/voice/speak': typeof ApiVoiceSpeakRoute
  '/api/webhooks/test': typeof ApiWebhooksTestRoute
  '/api/internal/webhooks/drain': typeof ApiInternalWebhooksDrainRoute
  '/api/souls/$soulId/events': typeof ApiSoulsSoulIdEventsRoute
  '/api/widgets/$soulId/session': typeof ApiWidgetsSoulIdSessionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-chatbot-trained-on-your-website'
    | '/ai-voice-agent-for-website'
    | '/app'
    | '/api/chat'
    | '/api/ingest'
    | '/api/scan'
    | '/api/workspace'
    | '/auth/$pathname'
    | '/widget/$soulId'
    | '/api/billing/cancel'
    | '/api/billing/change'
    | '/api/billing/checkout'
    | '/api/billing/confirm'
    | '/api/billing/invoices'
    | '/api/billing/summary'
    | '/api/billing/webhook'
    | '/api/chat/stream'
    | '/api/ingest/stream'
    | '/api/souls/$soulId'
    | '/api/souls/publish'
    | '/api/voice/clone'
    | '/api/voice/profiles'
    | '/api/voice/speak'
    | '/api/webhooks/test'
    | '/api/internal/webhooks/drain'
    | '/api/souls/$soulId/events'
    | '/api/widgets/$soulId/session'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-chatbot-trained-on-your-website'
    | '/ai-voice-agent-for-website'
    | '/app'
    | '/api/chat'
    | '/api/ingest'
    | '/api/scan'
    | '/api/workspace'
    | '/auth/$pathname'
    | '/widget/$soulId'
    | '/api/billing/cancel'
    | '/api/billing/change'
    | '/api/billing/checkout'
    | '/api/billing/confirm'
    | '/api/billing/invoices'
    | '/api/billing/summary'
    | '/api/billing/webhook'
    | '/api/chat/stream'
    | '/api/ingest/stream'
    | '/api/souls/$soulId'
    | '/api/souls/publish'
    | '/api/voice/clone'
    | '/api/voice/profiles'
    | '/api/voice/speak'
    | '/api/webhooks/test'
    | '/api/internal/webhooks/drain'
    | '/api/souls/$soulId/events'
    | '/api/widgets/$soulId/session'
  id:
    | '__root__'
    | '/'
    | '/ai-chatbot-trained-on-your-website'
    | '/ai-voice-agent-for-website'
    | '/app'
    | '/api/chat'
    | '/api/ingest'
    | '/api/scan'
    | '/api/workspace'
    | '/auth/$pathname'
    | '/widget/$soulId'
    | '/api/billing/cancel'
    | '/api/billing/change'
    | '/api/billing/checkout'
    | '/api/billing/confirm'
    | '/api/billing/invoices'
    | '/api/billing/summary'
    | '/api/billing/webhook'
    | '/api/chat/stream'
    | '/api/ingest/stream'
    | '/api/souls/$soulId'
    | '/api/souls/publish'
    | '/api/voice/clone'
    | '/api/voice/profiles'
    | '/api/voice/speak'
    | '/api/webhooks/test'
    | '/api/internal/webhooks/drain'
    | '/api/souls/$soulId/events'
    | '/api/widgets/$soulId/session'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiChatbotTrainedOnYourWebsiteRoute: typeof AiChatbotTrainedOnYourWebsiteRoute
  AiVoiceAgentForWebsiteRoute: typeof AiVoiceAgentForWebsiteRoute
  AppRoute: typeof AppRoute
  ApiChatRoute: typeof ApiChatRouteWithChildren
  ApiIngestRoute: typeof ApiIngestRouteWithChildren
  ApiScanRoute: typeof ApiScanRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  AuthPathnameRoute: typeof AuthPathnameRoute
  WidgetSoulIdRoute: typeof WidgetSoulIdRoute
  ApiBillingCancelRoute: typeof ApiBillingCancelRoute
  ApiBillingChangeRoute: typeof ApiBillingChangeRoute
  ApiBillingCheckoutRoute: typeof ApiBillingCheckoutRoute
  ApiBillingConfirmRoute: typeof ApiBillingConfirmRoute
  ApiBillingInvoicesRoute: typeof ApiBillingInvoicesRoute
  ApiBillingSummaryRoute: typeof ApiBillingSummaryRoute
  ApiBillingWebhookRoute: typeof ApiBillingWebhookRoute
  ApiSoulsSoulIdRoute: typeof ApiSoulsSoulIdRouteWithChildren
  ApiSoulsPublishRoute: typeof ApiSoulsPublishRoute
  ApiVoiceCloneRoute: typeof ApiVoiceCloneRoute
  ApiVoiceProfilesRoute: typeof ApiVoiceProfilesRoute
  ApiVoiceSpeakRoute: typeof ApiVoiceSpeakRoute
  ApiWebhooksTestRoute: typeof ApiWebhooksTestRoute
  ApiInternalWebhooksDrainRoute: typeof ApiInternalWebhooksDrainRoute
  ApiWidgetsSoulIdSessionRoute: typeof ApiWidgetsSoulIdSessionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-voice-agent-for-website': {
      id: '/ai-voice-agent-for-website'
      path: '/ai-voice-agent-for-website'
      fullPath: '/ai-voice-agent-for-website'
      preLoaderRoute: typeof AiVoiceAgentForWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-chatbot-trained-on-your-website': {
      id: '/ai-chatbot-trained-on-your-website'
      path: '/ai-chatbot-trained-on-your-website'
      fullPath: '/ai-chatbot-trained-on-your-website'
      preLoaderRoute: typeof AiChatbotTrainedOnYourWebsiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/widget/$soulId': {
      id: '/widget/$soulId'
      path: '/widget/$soulId'
      fullPath: '/widget/$soulId'
      preLoaderRoute: typeof WidgetSoulIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$pathname': {
      id: '/auth/$pathname'
      path: '/auth/$pathname'
      fullPath: '/auth/$pathname'
      preLoaderRoute: typeof AuthPathnameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/scan': {
      id: '/api/scan'
      path: '/api/scan'
      fullPath: '/api/scan'
      preLoaderRoute: typeof ApiScanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest': {
      id: '/api/ingest'
      path: '/api/ingest'
      fullPath: '/api/ingest'
      preLoaderRoute: typeof ApiIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/test': {
      id: '/api/webhooks/test'
      path: '/api/webhooks/test'
      fullPath: '/api/webhooks/test'
      preLoaderRoute: typeof ApiWebhooksTestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/speak': {
      id: '/api/voice/speak'
      path: '/api/voice/speak'
      fullPath: '/api/voice/speak'
      preLoaderRoute: typeof ApiVoiceSpeakRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/profiles': {
      id: '/api/voice/profiles'
      path: '/api/voice/profiles'
      fullPath: '/api/voice/profiles'
      preLoaderRoute: typeof ApiVoiceProfilesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/voice/clone': {
      id: '/api/voice/clone'
      path: '/api/voice/clone'
      fullPath: '/api/voice/clone'
      preLoaderRoute: typeof ApiVoiceCloneRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/souls/publish': {
      id: '/api/souls/publish'
      path: '/api/souls/publish'
      fullPath: '/api/souls/publish'
      preLoaderRoute: typeof ApiSoulsPublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/souls/$soulId': {
      id: '/api/souls/$soulId'
      path: '/api/souls/$soulId'
      fullPath: '/api/souls/$soulId'
      preLoaderRoute: typeof ApiSoulsSoulIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/ingest/stream': {
      id: '/api/ingest/stream'
      path: '/stream'
      fullPath: '/api/ingest/stream'
      preLoaderRoute: typeof ApiIngestStreamRouteImport
      parentRoute: typeof ApiIngestRoute
    }
    '/api/chat/stream': {
      id: '/api/chat/stream'
      path: '/stream'
      fullPath: '/api/chat/stream'
      preLoaderRoute: typeof ApiChatStreamRouteImport
      parentRoute: typeof ApiChatRoute
    }
    '/api/billing/webhook': {
      id: '/api/billing/webhook'
      path: '/api/billing/webhook'
      fullPath: '/api/billing/webhook'
      preLoaderRoute: typeof ApiBillingWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/summary': {
      id: '/api/billing/summary'
      path: '/api/billing/summary'
      fullPath: '/api/billing/summary'
      preLoaderRoute: typeof ApiBillingSummaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/invoices': {
      id: '/api/billing/invoices'
      path: '/api/billing/invoices'
      fullPath: '/api/billing/invoices'
      preLoaderRoute: typeof ApiBillingInvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/confirm': {
      id: '/api/billing/confirm'
      path: '/api/billing/confirm'
      fullPath: '/api/billing/confirm'
      preLoaderRoute: typeof ApiBillingConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/checkout': {
      id: '/api/billing/checkout'
      path: '/api/billing/checkout'
      fullPath: '/api/billing/checkout'
      preLoaderRoute: typeof ApiBillingCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/change': {
      id: '/api/billing/change'
      path: '/api/billing/change'
      fullPath: '/api/billing/change'
      preLoaderRoute: typeof ApiBillingChangeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/billing/cancel': {
      id: '/api/billing/cancel'
      path: '/api/billing/cancel'
      fullPath: '/api/billing/cancel'
      preLoaderRoute: typeof ApiBillingCancelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/widgets/$soulId/session': {
      id: '/api/widgets/$soulId/session'
      path: '/api/widgets/$soulId/session'
      fullPath: '/api/widgets/$soulId/session'
      preLoaderRoute: typeof ApiWidgetsSoulIdSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/souls/$soulId/events': {
      id: '/api/souls/$soulId/events'
      path: '/events'
      fullPath: '/api/souls/$soulId/events'
      preLoaderRoute: typeof ApiSoulsSoulIdEventsRouteImport
      parentRoute: typeof ApiSoulsSoulIdRoute
    }
    '/api/internal/webhooks/drain': {
      id: '/api/internal/webhooks/drain'
      path: '/api/internal/webhooks/drain'
      fullPath: '/api/internal/webhooks/drain'
      preLoaderRoute: typeof ApiInternalWebhooksDrainRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiChatRouteChildren {
  ApiChatStreamRoute: typeof ApiChatStreamRoute
}

const ApiChatRouteChildren: ApiChatRouteChildren = {
  ApiChatStreamRoute: ApiChatStreamRoute,
}

const ApiChatRouteWithChildren =
  ApiChatRoute._addFileChildren(ApiChatRouteChildren)

interface ApiIngestRouteChildren {
  ApiIngestStreamRoute: typeof ApiIngestStreamRoute
}

const ApiIngestRouteChildren: ApiIngestRouteChildren = {
  ApiIngestStreamRoute: ApiIngestStreamRoute,
}

const ApiIngestRouteWithChildren = ApiIngestRoute._addFileChildren(
  ApiIngestRouteChildren,
)

interface ApiSoulsSoulIdRouteChildren {
  ApiSoulsSoulIdEventsRoute: typeof ApiSoulsSoulIdEventsRoute
}

const ApiSoulsSoulIdRouteChildren: ApiSoulsSoulIdRouteChildren = {
  ApiSoulsSoulIdEventsRoute: ApiSoulsSoulIdEventsRoute,
}

const ApiSoulsSoulIdRouteWithChildren = ApiSoulsSoulIdRoute._addFileChildren(
  ApiSoulsSoulIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiChatbotTrainedOnYourWebsiteRoute: AiChatbotTrainedOnYourWebsiteRoute,
  AiVoiceAgentForWebsiteRoute: AiVoiceAgentForWebsiteRoute,
  AppRoute: AppRoute,
  ApiChatRoute: ApiChatRouteWithChildren,
  ApiIngestRoute: ApiIngestRouteWithChildren,
  ApiScanRoute: ApiScanRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  AuthPathnameRoute: AuthPathnameRoute,
  WidgetSoulIdRoute: WidgetSoulIdRoute,
  ApiBillingCancelRoute: ApiBillingCancelRoute,
  ApiBillingChangeRoute: ApiBillingChangeRoute,
  ApiBillingCheckoutRoute: ApiBillingCheckoutRoute,
  ApiBillingConfirmRoute: ApiBillingConfirmRoute,
  ApiBillingInvoicesRoute: ApiBillingInvoicesRoute,
  ApiBillingSummaryRoute: ApiBillingSummaryRoute,
  ApiBillingWebhookRoute: ApiBillingWebhookRoute,
  ApiSoulsSoulIdRoute: ApiSoulsSoulIdRouteWithChildren,
  ApiSoulsPublishRoute: ApiSoulsPublishRoute,
  ApiVoiceCloneRoute: ApiVoiceCloneRoute,
  ApiVoiceProfilesRoute: ApiVoiceProfilesRoute,
  ApiVoiceSpeakRoute: ApiVoiceSpeakRoute,
  ApiWebhooksTestRoute: ApiWebhooksTestRoute,
  ApiInternalWebhooksDrainRoute: ApiInternalWebhooksDrainRoute,
  ApiWidgetsSoulIdSessionRoute: ApiWidgetsSoulIdSessionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
